export const QUOTES = [
  "The secret of getting ahead is getting started. - Mark Twain",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Don't let what you cannot do interfere with what you can do. - John Wooden",
  "Strive for progress, not perfection.",
  "There are no shortcuts to any place worth going. - Beverly Sills",
  "Failure is the opportunity to begin again more intelligently. - Henry Ford",
  "Our greatest weakness lies in giving up. - Thomas Edison",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "The expert in anything was once a beginner. - Helen Hayes",
  "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
  "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
  "The beautiful thing about learning is that no one can take it away from you. - B.B. King",
  "Procrastination makes easy things hard and hard things harder. - Mason Cooley",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Motivation is what gets you started. Habit is what keeps you going. - Jim Ryun",
  "Don't wish it were easier; wish you were better. - Jim Rohn",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "If you can dream it, you can do it. - Walt Disney",
  "Everything you’ve ever wanted is on the other side of fear. - George Addair",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
  "Hard work beats talent when talent doesn't work hard. - Tim Notke",
  "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
  "The best way to predict the future is to create it. - Abraham Lincoln",
  "Do what you can, with what you have, where you are. - Theodore Roosevelt",
  "It is not the mountain we conquer, but ourselves. - Sir Edmund Hillary",
  "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
  "A person who never made a mistake never tried anything new. - Albert Einstein",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Don't wait. The time will never be just right. - Napoleon Hill",
  "Action is the foundational key to all success. - Pablo Picasso",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "What you do today can improve all your tomorrows. - Ralph Marston",
  "Aim for the moon. If you miss, you may hit a star. - W. Clement Stone",
  "Don't stop when you're tired. Stop when you're done.",
  "Focus on being productive instead of busy. - Tim Ferriss",
  "Discipline is doing what needs to be done, even if you don't want to do it.",
  "Small progress is still progress.",
  "Your education is a dress rehearsal for a life that is yours to lead. - Nora Ephron",
  "Genius is 1% inspiration and 99% perspiration. - Thomas Edison",
  "Learn as if you were to live forever. Live as if you were to die tomorrow. - Mahatma Gandhi",
  "The mind is not a vessel to be filled but a fire to be ignited. - Plutarch",
  "Teachers can open the door, but you must enter it yourself. - Chinese Proverb",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go. - Dr. Seuss",
  "Knowledge is power. - Francis Bacon",
  "Wisdom is not a product of schooling but of the lifelong attempt to acquire it. - Albert Einstein",
  "An investment in knowledge pays the best interest. - Benjamin Franklin",
  "The roots of education are bitter, but the fruit is sweet. - Aristotle",
  "Change is the end result of all true learning. - Leo Buscaglia",
  "Learning is never done without errors and defeat. - Vladimir Lenin",
  "The direction in which education starts a man will determine his future in life. - Plato"
];
